version: '3'

volumes:
  data:

services:
  app-backend-1:
    image: lucasmocerinomonteiro/payshare-backend:v2
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

  app-backend-2:
    image: lucasmocerinomonteiro/payshare-backend:v1
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}


  api-mercado-pago-1:
    image: lucasmocerinomonteiro/payshare-api-mercado-pago:v1
    ports:
      - 5000:${NODE_API_PORT}
    depends_on:
      - db
    environment:
      - NODE_HOSTNAME_DATABASE=db
      - NODE_DATABASE_NAME=${POSTGRES_BASE}
      - NODE_USERNAME=${POSTGRES_USERNAME}
      - NODE_PASSWORD=${POSTGRES_PASSWORD}
      - NODE_PORT_DATABASE=${POSTGRES_PORT}
      - PORT=${NODE_API_PORT}

  api-mercado-pago-2:
    image: lucasmocerinomonteiro/payshare-api-mercado-pago:v1
    ports:
      - 5001:${NODE_API_PORT}
    depends_on:
      - db
    environment:
      - NODE_HOSTNAME_DATABASE=db
      - NODE_DATABASE_NAME=${POSTGRES_BASE}
      - NODE_USERNAME=${POSTGRES_USERNAME}
      - NODE_PASSWORD=${POSTGRES_PASSWORD}
      - NODE_PORT_DATABASE=${POSTGRES_PORT}
      - PORT=${NODE_API_PORT}
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data